baseURL: "mariajosegonzalezfuentes.github.io" 
title: María José González-Fuentes
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 2
        - name: Resume
          url: resume/
          weight: 3
        - name: References
          url: references/
          weight: 4
        - name: Teaching
          url: teaching/
          weight: 5
    
params:
    description: "Economics PhD student at ENS Lyon and CERGIC"
    author: María José González-Fuentes
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["aboutme","workingpapers","workinprogress","teaching"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: María José González-Fuentes
          subtitle: "Hi! I am a PhD student in Economics at [**ENS de Lyon**](https://www.ens-lyon.fr/en/) and the [Center for Economic Research on Governance, Inequality and Conflict **CERGIC**](https://www.cergic-lyon.fr/), supervised by [**Sophie Hatte**](https://sites.google.com/site/sophiehatte/).<br><br> My main research interests are in **gender economics** and **political economy**. I also work on discrimination in the labor market using experimental methods. <br><br> Prior to my PhD I was as a pre-doctoral researcher at [**INSEAD**](https://www.insead.edu/faculty-research/academic-areas/economics-political-science) and the [**Women in Business Chair**](https://www.sciencespo.fr/women-in-business/en/) at Sciences Po. I also hold a Master's degree in Economics from [PSE](https://www.parisschoolofeconomics.eu/)."          
          # subtitle: "Hi! I am a PhD candidate in Economics at [**ENS de Lyon**](https://www.ens-lyon.fr/en/) and the [Center for Economic Research on Governance, Inequality and Conflict (CERGIC)](https://www.cergic-lyon.fr/). I am supervised by [**Sophie Hatte**](https://sites.google.com/site/sophiehatte/). <br><br> My research interests are in **gender economics** and **political economy**."
          # subtitle: "I am a **PhD candidate in Economics** at [ENS Lyon](https://www.ens-lyon.fr/en/) and [CERGIC](https://www.cergic-lyon.fr/).\n\nMy research interests are in **gender economics**, with a focus on the intersection of gender, politics and media. I am also interested in experimental and behavioral economics. I am supervised by [Sophie Hatte](https://sites.google.com/site/sophiehatte/).\n\nBefore starting my PhD, I was a pre-doc at INSEAD and a research assistant at the Women in Business Chair at Sciences Po ([LIEPP](https://www.sciencespo.fr/liepp/en/)).\n\nI hold a Master's degree in Analysis and Policy in Economics from the [Paris School of Economics (PSE)](https://www.parisschoolofeconomics.eu/)."
          imageUrl: "photo2024.jpg"
          imageTitle: María José González-Fuentes
          imageWidth: 160
          imageHeight: 160
          buttons:         
            - name: Research
              url: research/
            - name: Resume
              url: resume
            - name: References
              url: references/
            - name: Teaching
              url: teaching/

    socialIcons:
        - name: cv
          url: CV_2025.pdf
        - name: Email
          url: mailto:maria.gonzalez_fuentes@ens-lyon.fr
        - name: Bluesky
          url: https://bsky.app/profile/mariajose-gf.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "María José González-Fuentes"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
